import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, renameSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../../', import.meta.url));
const ddl = execFileSync(process.execPath, ['npm/crew/node_modules/drizzle-kit/bin.cjs', 'export', '--dialect=sqlite', '--schema=lib/database/schema.ts'], { cwd: root, encoding: 'utf8', timeout: 15000 });
if (!ddl.startsWith('CREATE TABLE')) throw new Error('unexpected schema export output');
const content = `// Generated by generate-schema.mjs; edit schema.ts instead.\nexport const SCHEMA_SQL = ${JSON.stringify(ddl.replace(/\n\);/g, '\n) STRICT;'))};\n`;
const target = new URL('./schema-ddl.ts', import.meta.url);
if (process.argv.includes('--check')) {
  if (readFileSync(target, 'utf8') !== content) throw new Error('schema-ddl.ts is stale; run generate-schema.mjs');
} else {
  const temp = new URL('./schema-ddl.ts.tmp', import.meta.url);
  writeFileSync(temp, content); renameSync(temp, target);
}
